# factor test
library(here)
library(haven)
library(SASxport)
source(here("programs", "R", "common.R"), encoding="utf-8")
ds_factor <- data.frame(c(rep(NA, length=10)))
ds_factor$test_col1 <- rep(1:3, length=10)
ds_factor$test_col1 <- labelled(ds_factor$test_col1, c(test1=1, test2=2, test3=3), label="てすと１")
ds_factor$test_col2 <- rep(c(0,1,9), length=10)
ds_factor$test_col2 <- labelled(ds_factor$test_col2, c(test1=0, test2=1, test3=9), label="てすと２")
ds_factor$default_T_1 <- haven::as_factor(ds_factor$test_col1, levels="default", ordered=T)
ds_factor$default_T_2 <- haven::as_factor(ds_factor$test_col2, levels="default", ordered=T)
ds_factor$default_T_1_num <- as.numeric(ds_factor$default_T_1)
ds_factor$default_T_2_num <- as.numeric(ds_factor$default_T_2)
ds_factor$default_F_1 <- haven::as_factor(ds_factor$test_col1, levels="default", ordered=F)
ds_factor$default_F_2 <- haven::as_factor(ds_factor$test_col2, levels="default", ordered=F)
ds_factor$default_F_1_num <- as.numeric(ds_factor$default_F_1)
ds_factor$default_F_2_num <- as.numeric(ds_factor$default_F_2)
ds_factor$labels_T_1 <- haven::as_factor(ds_factor$test_col1, levels="labels", ordered=T)
ds_factor$labels_T_2 <- haven::as_factor(ds_factor$test_col2, levels="labels", ordered=T)
ds_factor$labels_T_1_num <- as.numeric(ds_factor$labels_T_1)
ds_factor$labels_T_2_num <- as.numeric(ds_factor$labels_T_2)
ds_factor$labels_F_1 <- haven::as_factor(ds_factor$test_col1, levels="labels", ordered=F)
ds_factor$labels_F_2 <- haven::as_factor(ds_factor$test_col2, levels="labels", ordered=F)
ds_factor$labels_F_1_num <- as.numeric(ds_factor$labels_F_1)
ds_factor$labels_F_2_num <- as.numeric(ds_factor$labels_F_2)
ds_factor$values_T_1 <- haven::as_factor(ds_factor$test_col1, levels="values", ordered=T)
ds_factor$values_T_2 <- haven::as_factor(ds_factor$test_col2, levels="values", ordered=T)
ds_factor$values_T_1_num <- as.numeric(ds_factor$values_T_1)
ds_factor$values_T_2_num <- as.numeric(ds_factor$values_T_2)
ds_factor$values_F_1 <- haven::as_factor(ds_factor$test_col1, levels="values", ordered=F)
ds_factor$values_F_2 <- haven::as_factor(ds_factor$test_col2, levels="values", ordered=F)
ds_factor$values_F_1_num <- as.numeric(ds_factor$values_F_1)
ds_factor$values_F_2_num <- as.numeric(ds_factor$values_F_2)
ds_factor$both_T_1 <- haven::as_factor(ds_factor$test_col1, levels="both", ordered=T)
ds_factor$both_T_2 <- haven::as_factor(ds_factor$test_col2, levels="both", ordered=T)
ds_factor$both_T_1_num <- as.numeric(ds_factor$both_T_1)
ds_factor$both_T_2_num <- as.numeric(ds_factor$both_T_2)
ds_factor$both_F_1 <- haven::as_factor(ds_factor$test_col1, levels="both", ordered=F)
ds_factor$both_F_2 <- haven::as_factor(ds_factor$test_col2, levels="both", ordered=F)
ds_factor$both_F_1_num <- as.numeric(ds_factor$both_F_1)
ds_factor$both_F_2_num <- as.numeric(ds_factor$both_F_2)
ds_factor$ordered_1 <- base::ordered(rep(1:3, length=10), levels = c(1, 2, 3), labels=c("test1", "test2", "test3"))
ds_factor$ordered_2 <- base::ordered(rep(0:2, length=10), levels = c(0, 1, 2), labels=c("test1", "test2", "test3"))
ds_factor$ordered_1_num <- as.numeric(ds_factor$ordered_1)
ds_factor$ordered_2_num <- as.numeric(ds_factor$ordered_2)
ds_factor$base_factor_1 <- base::factor(rep(1:3, length=10), levels = c(1, 2, 3), labels=c("test1", "test2", "test3"), ordered=T)
ds_factor$base_factor_2 <- base::factor(rep(0:2, length=10), levels = c(0, 1, 2), labels=c("test1", "test2", "test3"), ordered=T)
ds_factor$base_factor_1_num <- as.numeric(ds_factor$base_factor_1)
ds_factor$base_factor_2_num <- as.numeric(ds_factor$base_factor_2)
ds_factor$base_factor_no_odr_1 <- base::factor(rep(1:3, length=10), levels = c(1, 2, 3), labels=c("test1", "test2", "test3"), ordered=F)
ds_factor$base_factor_no_odr_2 <- base::factor(rep(0:2, length=10), levels = c(0, 1, 2), labels=c("test1", "test2", "test3"), ordered=F)
ds_factor$base_factor_no_odr_1_num <- as.numeric(ds_factor$base_factor_no_odr_1)
ds_factor$base_factor_no_odr_2_num <- as.numeric(ds_factor$base_factor_no_odr_2)
ds_factor <- ds_factor[ , -1]
str(ds_factor)

write.xport(ds_factor, file=str_c(here("test", "factor_test"), "/test.xpt"))
